---
- name: "Install webservers"
  hosts: webservers
  become: true
  tasks:
    - name: "Install nginx"
      ansible.builtin.apt:
        name: nginx
        state: latest
      become: true
    - name: "Add custom header"
      ansible.builtin.lineinfile:
        path: /etc/nginx/sites-available/default
        insertafter: ^\s+listen\s\[::\]:80\sdefault_server;
        line: "       add_header X-Webserver {{ ansible_hostname }};" 
    - name: "Restart nginx daemon"
      ansible.builtin.systemd:
        name: nginx
        state: restarted
        enabled: true

- name: "Install HA"
  hosts: ha-proxies
  become: true
  tasks:
    - name: "Install HAPROXY"
      ansible.builtin.apt:
        name: haproxy
        state: latest
      become: true

    - name: "Get facts webservers group"
      ansible.builtin.setup:
      delegate_to: "{{ item }}"
      delegate_facts: true
      loop: "{{groups['webservers']}}"
      register: webservers_facts
    
    - name: "Add HAPROXY configuration"
      ansible.builtin.blockinfile:
        path: /etc/haproxy/haproxy.cfg
        block: |
          frontend LAB_FRONTEND
            description Frontend website1 et 2
            bind *:80
            mode http

          acl APP_LAB1 hdr_dom(host) -i website1.local
          use_backend LAB_BACKEND1 if APP_LAB1

          acl APP_LAB2 hdr_dom(host) -i website2.local
          use_backend LAB_BACKEND2 if APP_LAB2

          
          backend LAB_BACKEND1
          description Backend {{ webservers_facts.results[0]['ansible_facts']['ansible_hostname'] }}
          server {{webservers_facts.results[0]['ansible_facts']['ansible_hostname']}} {{webservers_facts.results[0]['ansible_facts']['ansible_eth1']['ipv4']['address']}}:80 

          backend LAB_BACKEND2
          description {% for server in webservers_facts.results %}{% if loop.first != True %}{{server['ansible_facts']['ansible_hostname']}}{% endif %} {% endfor %}


          {% for server in webservers_facts.results %}
            {% if loop.first != True %}
              server {{server['ansible_facts']['ansible_hostname']}} {{server['ansible_facts']['ansible_eth1']['ipv4']['address']}}:80 
            {% endif %}
          {% endfor %}

          listen stats
            bind *:9000
            stats enable
            stats uri /stats
            stats refresh 2s
            stats show-desc
            stats show-legends
            stats auth vincent:P@ssw0rd
            stats admin if TRUE
    - name: "Restart HAPROXY"
      ansible.builtin.systemd:
        name: haproxy
        state: restarted
        enabled: true
            
