Vagrant.configure("2") do |config|
    config.vm.define "web" do |server|
      server.vm.box = "debian/bullseye64"
      server.vm.network :private_network, :ip => "10.10.0.2", :libvirt__domain_name => "test.local"
      server.vm.hostname = "web"
    end

    config.vm.define "HA" do |server|
      server.vm.box = "debian/bullseye64"
      server.vm.network :private_network, :ip => "10.10.0.3", :libvirt__domain_name => "test.local"
      server.vm.hostname = "HA"
    end
    
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook-provisionning.yml"
    ansible.groups = {
      "webservers" => ["web"],
      "ha-proxies" => ["HA"]
    }
  end
end