Vagrant.configure("2") do |config|
  (1..3).each do |i|
      config.vm.define "web-#{i}" do |server|
          server.vm.box = "debian/bullseye64"
          server.vm.network :private_network, :ip => "10.10.0.#{i+1}", :libvirt__domain_name => "test.local"
          server.vm.hostname = "web-#{i}"
      end
  end

  (1..2).each do |i|
    config.vm.define "HA-#{i}" do |server|
          server.vm.box = "debian/bullseye64"
          server.vm.network :private_network, :ip => "10.10.0.#{i+4}", :libvirt__domain_name => "test.local"
          server.vm.hostname = "HA-#{i}"
      end
    end
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook-provisionning.yml"
    ansible.groups = {
      "webservers" => ["web-[1:3]"],
      "ha-proxies" => ["HA-[1:2]"]
    }
  end
end