Vagrant.configure("2") do |config|
  (1..4).each do |i|
      config.vm.define "web-#{i}" do |server|
          server.vm.box = "debian/bullseye64"
          server.vm.network :private_network, :ip => "10.10.0.#{i+1}", :libvirt__domain_name => "test.local"
          server.vm.hostname = "web-#{i}"
      end
  end

  (1..2).each do |i|
    config.vm.define "HA-#{i}" do |server|
          server.vm.box = "debian/bullseye64"
          server.vm.network :private_network, :ip => "10.10.0.#{i+5}", :libvirt__domain_name => "test.local"
          server.vm.hostname = "HA-#{i}"
      end
    end
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook-provisionning.yml"
    ansible.host_vars = {
      "HA-1" => {"keepalived_role" => "MASTER"},
      "HA-2" => {"keepalived_role" => "SLAVE"}
    }
    ansible.groups = {
      "webservers" => ["web-[1:4]"],
      "ha-proxies" => ["HA-[1:2]"],
      "ha-proxies:vars" => {"keepalived_pass" => "P@ssw0rd"}
    }
  end
end